### ISSUE TITLE
Application looks like it stopped with installing process

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/feathers-sdk-manager#4]
There is message "Installing Feathers SDK", and for some longer time it just stays there without any further progress.

Here is screenshot:
![image](https://cloud.githubusercontent.com/assets/1468887/8582401/db65fe7e-25c6-11e5-8721-f0df805e4e6f.png)

Is there any log to check out for error messages?

**Comment by joshtynjala** [comment]
I added #2 earlier today where I plan to expose the log somehow. It just didn't make it into the first version.

Just to be clear, did your installation ever complete? Or is it simply that it looks stuck for a short time?

**Comment by neminovno** [comment]
Installation did not complete. Application stucked forever. Also, could not close it using X button. After closing it with Task Manager, and running it second time, installation was successful.

**Comment by joshtynjala** [comment]
Okay, thanks! Once I expose the logs, you'll be able to share them with me when something goes wrong. For now, I have some analytics set up, which should include errors. I plan to look through the analytics later today or tomorrow. If there was a runtime error, it probably got saved for me already, so that might help a bit.

I'm glad that the installation worked out for you the second time. If you have any suggestions or other feedback, please let me know!

**Comment by joshtynjala** [comment]
In version 1.1.0, you may now abort an installation if it gets stuck. Additionally, after you abort, you will see an option to read the log.

If it gets stuck like that again, please try to share the log. Thanks!

**Comment by JustinWalkerThotkraft** [comment]
Josh my feathers installer has been stuck for several hours.
I aborted.

Here is a copy of the log:
Feathers SDK Manager 1.1.1 windows
Loading configuration file: http://feathersui.com/sdk/feathers-sdk-manager/sdk-manager-config-1.0.xml
Configuration file loaded successfully.
Configuration file parsed successfully.
Loading product from URL: https://github.com/BowlerHatLLC/feathers-sdk/releases/download/v2.2.0/feathers-sdk-2.2.0-bin.zip
Product loaded successfully.
Decompressing product.
Installation of Feathers SDK aborted.

Im on Windows 7.

**Comment by JustinWalkerThotkraft** [comment]
Josh my feathers installer has been stuck for several hours.
I aborted.

Here is a copy of the log:
Feathers SDK Manager 1.1.1 windows
Loading configuration file: http://feathersui.com/sdk/feathers-sdk-manager/sdk-manager-config-1.0.xml
Configuration file loaded successfully.
Configuration file parsed successfully.
Loading product from URL: https://github.com/BowlerHatLLC/feathers-sdk/releases/download/v2.2.0/feathers-sdk-2.2.0-bin.zip
Product loaded successfully.
Decompressing product.
Installation of Feathers SDK aborted.

Im on Windows 7.

**Comment by joshtynjala** [comment]
Thanks! I'll see if I can reproduce. It might just be a bad download, though. Have you tried more than once?

**Comment by JustinWalkerThotkraft** [comment]
Thank you very much.
I've tried twice, I think.

**Comment by joshtynjala** [comment]
Unfortunately, I wasn't able to reproduce the issue on Windows 7. In the next update of Feathers SDK Manager, the log will include the size of the downloaded file. If it's not the expected number of bytes, that might give us a clue about why it's not decompressing.

**Comment by JustinWalkerThotkraft** [comment]
Thank you so much for your help.

**Comment by neminovno** [comment]
It happened to me again. Where can I find log?

**Comment by neminovno** [comment]
I could not find log file, and I tried again. Now, twice in a row it was successful. As I remember, if that can help you, last line in failed attempt log was:
"air-setup-mac:"

**Comment by JustinWalkerThotkraft** [comment]
Theres a show logs button in the bottom left of the screen when you abort.
Josh, it appears to be working again.  I think it may either be an internet or server-side issue.

The client appears to work fine.
Thank you again for your help.

**Comment by neminovno** [comment]
JustinWalkerThotkraft I wanted to find it after I closed app. Thanks.
