### ISSUE TITLE
Compiling issues.

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers-sdk-manager#5]
Using this project as an example how to run a similar setup as to one of our apps. I've never been able to compile out of the box without commenting out some errors but would like to be able to rectify that.

Currently I have 2 compiler errors (not including errors due to SDK 2.3.0).

**1. Error:(103, 33) [zFeathersSDKManager]: Error code: 1119: Access of possibly undefined property nativeWindow through a reference with static type flash.display:Stage.**

In this case it's saying the properly "nativeWindow" doesn't exist. - Starling is imported as part of the SDK (my understanding) so I'm not sure why my version would differ?

**2. Error:(103, 82) [zFeathersSDKManager]: Error code: 1119: Access of possibly undefined property CLOSING through a reference with static type Class.**

In this case the constant "CLOSING" does not exist. Looking at the Event class in AIR 19 - the closes event to that would be "CLOSE". thoughts?

Thanks Josh!

**Comment by joshtynjala** [comment]
It appears that you are not compiling for Adobe AIR. nativeWindow is only available in AIR, and if you compile for Flash Player, referencing this property will result in a compiler error. This is not a Starling issue. That's an AIR runtime API.

Strangely, the Flash API reference does not mark Event.CLOSING as an AIR-only API. However, with a quick test, I can see that it only seems to work when compiling for AIR. So it seems to be the same issue.

How are you trying to compile? On the command line? With the build.xml Ant script? In an IDE like Flash Builder or IntelliJ IDEA?

**Comment by izzmeifter** [comment]
Sorry about confusing the issue with the starling comment. the line that errors is Starling.current.nativeStage.nativeWindow.addEventListener(flash.events.Event.CLOSING, nativeWindow_closingHandler, false, 0, true);

so Starling is referencing the properly.

I am compiling for AIR using IntelliJ (I can't even tell you the last time I compiled to anything but ;) -  I have included the libs (Seen below) - I have included libs from 2.3.0 but am compiling w/2.2.0

![screen shot 2015-11-03 at 10 51 17 am](https://cloud.githubusercontent.com/assets/4297079/10916487/e4a44686-8218-11e5-99ee-6d1748cdd23a.png)

**Comment by izzmeifter** [comment]
Ahh, and there in lies the problem. I was importing the player/19.0 and that's overriding the air player I suppose. sorry, I thought I read somewhere in the case of Feather SDK and IntelliJ we needed to import  those without really thinking about it much.

Let me test without that import.

**Comment by izzmeifter** [comment]
Okay that works, now I'm down to this (sorry)

**Error:(331, 53) [zFeathersSDKManager]: Error code: 1119: Access of possibly undefined property STANDARD_ERROR_DATA through a reference with static type Class.**

from this line

``` actionscript
this._process.addEventListener(ProgressEventData.STANDARD_ERROR_DATA, decompress_errorHandler, false, 0, true);
```

Looking inside your ProgressEventData class there are no constants.

``` actionscript
package events
{
    public class ProgressEventData
    {
        public function ProgressEventData(progress:Number, label:String)
        {
            this.progress = progress;
            this.label = label;
        }

        public var progress:Number;
        public var label:String;
    }
}
```

**Comment by joshtynjala** [comment]
The libs/air and libs/player folders do not need to be added. The other SWCs in libs need to be added for IntellIJ to realize that they contain MXML components.

**Comment by joshtynjala** [comment]
It appears that you have accidentally modified the code:

```
this._process.addEventListener(ProgressEvent.STANDARD_ERROR_DATA, decompress_errorHandler, false, 0, true);
```

**Comment by izzmeifter** [comment]
Oh for crying out loud. I have no clue how that happened :( -  Sorry to bug you Josh. I owe you a beer someday. Thanks.

**Comment by joshtynjala** [comment]
No problem. I'm glad that you figured it out!
