### ISSUE TITLE
Manager not pulling SDK

### ISSUE THREAD

**Issue by urthling** [BowlerHatLLC/feathers-sdk-manager#9]
Hey Josh!

I should have kept a copy of the downloaded files.. 

I thought perhaps there might be a few key presses to get to change the path..

Will you be updating the manager?

**Comment by joshtynjala** [comment]
Sorry about that! I moved some repositories around on Github the other day, and some of the URLs from the website didn't get updated correctly. It's now fixed, and I can confirm that I was able to install an SDK using the manager.

**Comment by joshtynjala** [comment]
For completeness, in case things break and this ends up as a Google result, it is possible to provide custom download URLs for everything, including the Feathers SDK and the AIR SDK. The manager downloads this config file from the Feathers UI website:

https://feathersui.com/sdk/feathers-sdk-manager/sdk-manager-config-1.0.xml

You can download the same file manually and create a modified version. It's possible to pass in a local file system path as a command line option.

```
FeathersSDKmanager.exe -config path/to/sdk-manager-config-1.0.xml
```

**Comment by urthling** [comment]
Ah, fabulous!  Yes, working like a charm again, thank you as always for your quick response.

And spot on, good to know!
